EFCoreMvcProject/Pages/ListOfEmployees/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EFCoreMvcProject.Models;
using EFCoreMvcProject.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EFCoreMvcProject.Pages.ListOfEmployees
{
    public class DeleteModel : PageModel
    {
        private readonly ItuseTheProgrammerRepo _tuseRepo;
        [BindProperty]
        public Employee Employee { get; set; }
        public DeleteModel(ItuseTheProgrammerRepo ituseRepo)
        {
            _tuseRepo = ituseRepo;
        }
  
        public IActionResult OnGet(int id)
        {
            Employee = _tuseRepo.FindEmployeeById(id);
            if (Employee != null)
            {
                return Page();
            }
            else
            {
                return RedirectToPage("/ErrorHandler/Error");
            }
        }

        public IActionResult OnPost()
        {
            Employee = _tuseRepo.DeleteExistingEmployee(Employee.Id);
            if(Employee != null)
            {
                return RedirectToPage("Index");
            }
            else
            {
                return RedirectToPage("/ErrorHandler/Error");
            }
        }
    }
}

EFCoreMvcProject/Pages/ListOfEmployees/Details.cshtml.cs
using EFCoreMvcProject.Models;
using EFCoreMvcProject.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ActionConstraints;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EFCoreMvcProject.Pages.ListOfEmployees
{
    public class DetailsModel : PageModel
    {
        private readonly ItuseTheProgrammerRepo _tuseRepo;
        public Employee Employee { get; set; }
       
        [TempData]
        public string Message { get; set; }
        public DetailsModel(ItuseTheProgrammerRepo ituseRepo)
        {
            _tuseRepo = ituseRepo;
        }
        public IActionResult OnGet(int id)
        {
            Employee = _tuseRepo.FindEmployeeById(id);
            if(Employee != null)
            {
                return Page();
            }
            else
            {
                return RedirectToPage("/ErrorHandler/Error");
            }
        }
    }
}

EFCoreMvcProject/Pages/ListOfEmployees/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using EFCoreMvcProject.Models;
using EFCoreMvcProject.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EFCoreMvcProject.Pages.ListOfEmployees
{
    public class EditModel : PageModel
    {
        private readonly ItuseTheProgrammerRepo _tuseRepo;
        [BindProperty]
        public Employee Employee { get; set; }
        [BindProperty]
        public bool Notify { get; set; }
        [BindProperty]
        public string Message { get; set; }

        //[Display(Name ="Photo")]
        //public IFormFile FormFileImage { get; set; }
        public EditModel(ItuseTheProgrammerRepo ituseRepo)
        {
            _tuseRepo = ituseRepo;
        }
        public IActionResult OnGet(int? id)
        {
            if (id.HasValue)
            {
                Employee = _tuseRepo.FindEmployeeById(id.Value);
            }
            else
            {
                Employee = new Employee();
            }

            if (Employee != null)
            {
                return Page();
            }
            else
            {
                return RedirectToPage("/ErrorHandler/Error");
            }
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                if (Employee.Id > 0)
                {
                    Employee = _tuseRepo.UpdateEmployee(Employee);
                }
                else
                {
                    Employee = _tuseRepo.CreateNewEmployee(Employee);
                }
                if (Employee != null)
                {
                    return RedirectToPage("Index");
                }
                else
                {
                    return RedirectToPage("/ErrorHandler/Error");
                }
            }
            return Page();
        }

        public IActionResult OnPostUpdateNotificationPreferences(int id)
        {
            if (Notify)
            {
                Message = "Thank you for turning on notifications!";
            }
            else
            {
                Message = "You have turned off email notifications!";
            }
            TempData["message"] = Message;

            return RedirectToPage("Details", new { id = id });

        }


    }
}

EFCoreMvcProject/Pages/ListOfEmployees/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EFCoreMvcProject.Models;
using EFCoreMvcProject.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EFCoreMvcProject.Pages.ListOfEmployees
{
    public class IndexModel : PageModel
    {
        private readonly ItuseTheProgrammerRepo _tuseRepo;
        public IEnumerable<Employee> Employees { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SearchForEmployee { get; set; }
        public IndexModel(ItuseTheProgrammerRepo ituseRepo)
        {
            _tuseRepo = ituseRepo;
        }
        public IActionResult OnGet()
        {

            Employees = _tuseRepo.Search(searchTerm: SearchForEmployee);
            if (Employees != null)
            {
                return Page();
            }
            else
            {
                return RedirectToPage("/ErrorHandler/Error");
            }
        }
    }
}

EFCoreMvcProject/ViewComponents/HeadCountViewComponent.cs
using EFCoreMvcProject.Models;
using EFCoreMvcProject.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFCoreMvcProject.ViewComponents
{
    public class HeadCountViewComponent : ViewComponent
    {
        private readonly ItuseTheProgrammerRepo _ituse;

        public HeadCountViewComponent(ItuseTheProgrammerRepo ituse)
        {
            _ituse = ituse;
        }
        public IViewComponentResult Invoke(Department.Dept? departmentName = null)
        {
            var result = _ituse.DepartmentHeadCounts(departmentName);
            return View(result);
        }
    }
}

EFCoreMvcProject/Pages/ListOfEmployees/Delete.cshtml
@page "/employee/delete/{id:min(1)}"
@model EFCoreMvcProject.Pages.ListOfEmployees.DeleteModel
@{
    ViewData["Title"] = "Delete Employee";
    ViewData["ShowButtons"] = false;
}

<h2 class="text-primary">
    Delete confirmation
</h2>
<hr />
<div class="alert alert-danger">
    <partial name="_DisplayEmployeePartial" model="@Model.Employee" view-data="ViewData" />
    <h5>
        Are you sure you want to delete employee - @Model.Employee.Name?
    </h5>
    <form method="post">
        <input hidden="hidden" asp-for="Employee.Id" />
        <input type="submit" class="btn btn-outline-danger" value="Yes" />
        <a class="btn btn-outline-secondary" asp-page="/ListOfEmployees/Index">No</a>
    </form>
</div>

EFCoreMvcProject/Pages/ListOfEmployees/Details.cshtml
@page "/employee/view/{id:int}"
@model EFCoreMvcProject.Pages.ListOfEmployees.DetailsModel
@{
    ViewData["Title"] = "Employee Details";
    string phonePath = "~/images/" + (Model.Employee.Photo ?? "jjc.jpg");
}

<style>
    .btn {
        width: 75px;
    }
</style>
<h2 class="text-primary">
    Employee details
</h2>
<hr />
<div class="row justify-content-center">
    @if (Model.Message != null)
    {
        <div class="col-sm-8">
            <div class="alert alert-primary">
                @Model.Message
            </div>
        </div>
    }
    <div class="col-md-8">
       @*@await Component.InvokeAsync("HeadCount", new { department = Model.Employee.Dept })*@
      <vc:head-count department-name="@Model.Employee.Dept"></vc:head-count>
    </div>
    <div class="col-md-8">
        <div class="card-deck mt-2">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-primary text-center">@Model.Employee.Name</h2>
                </div>
                <div class="card-body text-center text-primary">
                    <img src="@phonePath" asp-append-version="true" class="img-thumbnail card-img-top" />
                    <h4 class="card-title">
                        Employee Id : @Model.Employee.Id
                    </h4>
                    <h4 class="card-title">
                        Email : @Model.Employee.Email
                    </h4>
                    <h4 class="card-title">
                        Department : @Model.Employee.Dept
                    </h4>
                    <h4 class="card-title">
                        Salary : @Model.Employee.Salary.Value.ToString("c")
                    </h4>
                </div>
                <div class="card-footer text-center">
                    <a class="btn btn-secondary mt-2" asp-page="/ListOfEmployees/Index" style="width:auto">Cancel</a>
                    <a asp-route-id="@Model.Employee.Id" class="btn btn-primary mt-2" asp-page="Edit">Edit</a>
                    <a class="btn btn-danger text-white mt-2" asp-route-id="@Model.Employee.Id" asp-page="Delete">Delete</a>
                </div>
            </div>
        </div>


    </div>


</div>

EFCoreMvcProject/Pages/ListOfEmployees/Edit.cshtml
@page "/employee/edit/{id:int:min(1)?}/{handler?}"
@model EFCoreMvcProject.Pages.ListOfEmployees.EditModel
@{
    ViewData["Title"] = "Edit";
    //string phonePath = "~/images/" + (Model.Employee.Photo ?? "jjc.jpg");
    string pageHandler = Model.Employee.Id > 0 ? "Edit" : "Create new employee";
}

<h2 class="text-primary">
   @pageHandler
</h2>
<hr />
<h1 class="text-primary">Notification Preferences</h1>
<form method="post" asp-page-handler="UpdateNotificationPreferences">
    <div class="form-check">
        <input asp-for="Notify" class="form-check-input" />
        <label asp-for="Notify" class="form-check-label">
            Received email notification when my details change
        </label>
    </div>
    <button class="btn btn-outline-primary" type="submit">
        Update Notification Preferences
    </button>
    <div asp-validation-summary="All" class="text-danger"></div>
</form>

<hr />
<form method="post" class="mt-3" asp-page-handler="OnPost">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input hidden="hidden" asp-for="Employee.Id" />
    <div class="row form-group">
        <label asp-for="Employee.Name" class="col-form-label col-md-2"></label>
        <div class="col-sm-10">
            <input asp-for="Employee.Name" class="form-control" placeholder="Name..." />
            <span asp-validation-for="Employee.Name" class="text-danger"></span>
        </div>
    </div>
    <div class="row form-group">
        <label asp-for="Employee.Email" class="col-form-label col-md-2"></label>
        <div class="col-sm-10">
            <input asp-for="Employee.Email" class="form-control" placeholder="Email..." />
            <span asp-validation-for="Employee.Email" class="text-danger"></span>
        </div>
    </div>
    @*<div class="form-group row">
            <label asp-for="FormFileImage" class="col-form-label col-md-2"></label>
            <div class="col-sm-10">
                <div class="custom-file">
                    <input asp-for="FormFileImage" class="form-control custom-file-input" multiple/>
                    <label class="custom-file-label">Click here to change photo...</label>
                </div>
            </div>

        </div>*@
    <div class="row form-group">
        <label asp-for="Employee.Salary" class="col-form-label col-md-2"></label>
        <div class="col-sm-10">
            <input asp-for="Employee.Salary" class="form-control" placeholder="Salary..." />
            <span asp-validation-for="Employee.Salary" class="text-danger"></span>
        </div>
    </div>
    <div class="row form-group">
        <label class="col-form-label col-md-2" asp-for="Employee.Dept"></label>
        <div class="col-sm-10">
            <select asp-for="Employee.Dept" asp-items="Html.GetEnumSelectList<Department.Dept>()" class="custom-select">
                <option value="">Select your department</option>
            </select>
            <span asp-validation-for="Employee.Dept" class="text-danger"></span>
        </div>
    </div>
    @*<div class="row justify-content-center"><img src="@phonePath" class="imageThumnails rounded-circle" asp-append-version="true" /></div>*@
    <div class="row form-group">
        <div class="col-sm-10">
            <input type="submit" class="btn btn-outline-success" value="Create" />
            <a asp-page="/ListOfEmployees/Index" class="btn btn-outline-secondary">Cancel</a>
        </div>
    </div>

</form>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileLabel = $(this).next('.custom-file-label');
                var files = $(this)[0].files;
                if (files.length > 1) {
                    fileLabel.html(files.length + ' files selected');
                }
                else if (files.length == 1) {
                    fileLabel.html(files[0].name);
                }
            });
        });
    </script>
    <partial name="_ValidationScriptsPartial" />

}

EFCoreMvcProject/Pages/ListOfEmployees/Index.cshtml
@page "{id:int?}"
@model EFCoreMvcProject.Pages.ListOfEmployees.IndexModel
@{
    ViewData["Title"] = "List Of Employees";
    ViewData["ShowButtons"] = true;
}
<style>
    .btn {
        width: 75px;
    }
</style>
<h2 class="text-primary">
    List Of Employees
</h2>
<hr />
<form method="get">
    <div class="input-group">
        <input class="form-control" placeholder="Search..." asp-for="SearchForEmployee" />
        <div class="input-group-append">
            <button class="btn btn-outline-primary" type="submit">
                Search
            </button>
        </div>
    </div>

</form>
@*@await Component.InvokeAsync("HeadCount")*@
<vc:head-count department-name="@null"></vc:head-count>
@if (Model.Employees.Any())
{
    <div class="card-deck text-primary">
        @foreach (var emp in Model.Employees)
        {
            <partial name="_DisplayEmployeePartial" model="emp" view-data="ViewData" />
        }


    </div>


}
else
{
    <div class="card">
        <div class="card-header">
            <h2>No employee has been added yet.</h2>
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to create an Employee
            </h5>
        </div>
        <div class="card-footer">
            <a asp-page="Edit" class="btn btn-outline-info">Create</a>
        </div>
    </div>
}